### ISSUE TITLE
index() does not work when called within .map() 

### ISSUE THREAD

**Issue by andresfchamorro** [davemlz/eemont#2] opened 2021-04-13 18:39 UTC
Hey!

First of all great work, very useful package. I am trying to create a time series dataset of indices based on Landsat collections. I have prepared a basic function that works well when it's run with one feature, but it fails when mapped to a feature collection. Here is a simplified version of the function:

```python
def getStats(feature):
    oliCol = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR').filterBounds(feature.geometry()).filterDate('2013-01-01','2015-01-01')
    oliNDVI = oliCol.scale().index('NDVI').select('NDVI').toBands()
    zs = ee.Image(oliNDVI).reduceRegion(
        geometry = feature.geometry(),
        reducer = ee.Reducer.mean(),
        scale = 1000,
        tileScale = 4,
        bestEffort = True,
        maxPixels = 10e15
    )
    return feature.setMulti(zs)
```
This works: 
```python
res = getStats(aoi)
```
But this fails:
```python
res = AOIs.map(getStats)
```
with the following error

![image](https://user-images.githubusercontent.com/19510711/114603415-b0657080-9c65-11eb-96e4-0d396d364d35.png)

Something is happening that prevents _get_platform from running properly. Is this expected? Any ideas how to fix?

**Comment by davemlz** [comment] 2021-04-13 20:07
Hi Andres!

Thank you very much for pointing this out, I will check it. Is there any chance I can get access to the feature collection to try it?

In the meantime, let me tell you that you can get the time series from a feature collection by using the `getTimeSeriesByRegions()` method from eemont 0.1.9 ([example here](https://github.com/davemlz/eemont/blob/master/tutorials/014-Time-Series-By-Regions-Pandas.ipynb)):

```python
oliCol = (ee.ImageCollection('LANDSAT/LC08/C01/T1_SR')
   .filterBounds(featurecollection)
   .filterDate('2013-01-01','2015-01-01')
   .scale()
   .index('NDVI'))

ts = oliCol.getTimeSeriesByRegions(collection = featurecollection,
   reducer = ee.Reducer.mean(),
   bands = 'NDVI',
   scale = 1000,
   tileScale = 4)
```

Let me know if it works! And I will check the error to see what's happening.

Cheers!

**Comment by andresfchamorro** [comment] 2021-04-14 14:43
Thanks, I'll look into getTimeSeriesByRegions. I am doing a bit of harmonization prior (merging different Landsat collections) and running this for multiple countries, which is why I was implementing a custom function - if I don't use filterBounds for each country it will probably time out.

Sure, send me your gmail and I'll share the feature collection.

**Comment by davemlz** [comment] 2021-04-15 01:38
Hi Andres!

Ok, now I understand.

You can share your feature collection to this [gmail](mailto:dml.mont@gmail.com).

Thanks!

**Comment by davemlz** [comment] 2021-04-19 02:32
Hi Andres!

I have checked your script, and now I know what's happening: The problem is associated to the _get_platform function. This function uses the `getInfo()` client method in order to get the ID of the ee.Image (or ee.ImageCollection) so different `eemont` methods such as `scale()`, `maskClouds()` or `index()` can be computed according to the parameters of the specific satellite platform.

Since `getInfo()` is a client method and not a server method, it can't be mapped (it can't be used within a `map()` function). Check the [Debugging Guide](https://developers.google.com/earth-engine/guides/debugging#mapped-functions).

In this case, the problem can be solved by working in the client-side and not in the server-side. This works perfectly:

```python
countries = ['Ethiopia','Ghana','Nicaragua'] # client-side object, don't use here an ee.List since it is a server-side object
features = []
for country in countries: # client-side loop
    # Here, the name of each country (a client-side object)
    # is used to filter the feature collection and a
    # server-side object is retrieved (an ee.Feature)
    # and it is appended to the list
    features.append(getStats(AOIs.filterMetadata('WB_ADM0_NA', 'equals',country)))
# Here, the list of ee.Feature objects is converted into an ee.FeatureCollection
ee.FeatureCollection(features)
```

I'll close this issue for now and I'll open a new issue regarding the use of the `getInfo()` method inside the `_get_platform` function. I hope to find a way to use just server-side methods inside eemont soon.

Thank you very much for your time and attention here!

Cheers!

**Closed by davemlz** 2021-04-19 02:32 UTC
